# Generated by Django 5.2.17 on 2026-09-13 01:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('design', 'Graphic Design'), ('soft-skill', 'Soft Skill'), ('language', 'Language'), ('drawing', 'Drawing/Painting')], default='design', max_length=20)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
