# Generated by Django 5.2.17 on 2026-09-20 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('kti', 'Karya Tulis Ilmiah'), ('hackathon', 'Hackathon'), ('poster', 'Poster'), ('business case', 'Business Case'), ('olimpiade', 'Olimpiade')], default='hackathon', max_length=50)),
                ('description', models.TextField()),
                ('position', models.CharField(max_length=255)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('timestamp_achieved', models.PositiveIntegerField()),
                ('timestamp_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
